export PYENV_ROOT="$HOME/.pyenv"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  export PATH="$HOME/.linuxbrew/bin/:$PYENV_ROOT/bin:$PATH"
else
  export PATH="$PYENV_ROOT/bin:$PATH"  
fi
eval "$(pyenv init --path)"
